### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by vaniron** [qwbarch/ShinyToken#1]
Not working on latest reforged 8.0.2: https://pastebin.com/raw/2rYuhfPU

**Comment by qwbarch** [comment]
I'm unable to reproduce this issue on reforged 8.0.2. In fact, that's the version I created it on.
Maybe it has a conflict with PixelOptimizer? I'm assuming that's a private mod as I'm unable to find it through a google search.

**Comment by vaniron** [comment]
Nope, even with forge and pixelmon only it does not work - same error. What forge are you using? I am on recommended 2854.

**Comment by qwbarch** [comment]
I was able to reproduce the issue this time. Turns out it was a silly mistake, I didn't realize kotlin library isn't shipped with the mod by default. 
The reason it worked fine for myself was because I was using a 3rd-party mod that bundles the kotlin library.
I recommend downloading [Shadowfact's Forgelin](https://www.curseforge.com/minecraft/mc-mods/shadowfacts-forgelinl) to resolve the crash.
I'll be updating the modpage to show this as well, thanks for reporting the bug!
